-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8dEEQTMTFq4htNl8
BnLkycpKFfxWKW3qD6krzh/akFugCgYIKoZIzj0DAQehRANCAATHNXOuZTpV+Bbm
Ah1lvXwLW7whTFwlZqGG5Zo/3jgwP+R/fzWiO1oyONiPfVw4Po9ekFf3pLoFuCY0
uBTTLh8L
-----END PRIVATE KEY-----