-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzPEHfd72OtdTdw67
nIyQWjAPiKiSiSUM01vNSB2l2QGgCgYIKoZIzj0DAQehRANCAAQgFEOthUwyNDLu
6myvRXatUD2ASb7Qv+MNQAtzR7GC0qAz3wUJXcPH/kdBDtrA5tYIlp0Z75DZciSr
bBy61/ql
-----END PRIVATE KEY-----